### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by bsg-marvin** [danieljtribe/homebridge-agile-octopus#1]
Hi, this is great - thank you. Is there a chance to create it as a thermometer or something what would show actual rate?

Thanks

**Comment by bsg-marvin** [comment]
Just figured it actually shows actual rate.

**Comment by danieljtribe** [comment]
Evening! Thanks, glad you like it. 
I really wish Apple would support a wider range of devices so we could use something more appropriate for the current price, but the thermometer is the best thing for the job at the moment.

If you’ve got any ideas for improvements I’d be very glad to add them to the plug-in 🙂

-Dan

**Comment by bsg-marvin** [comment]
If I could suggest one thing - there could be settings to disable switches completely. I will use Home+ for automations where you can set triggers by value. Also not to round price would be helpful. Thank you for investing your time into this.

Filip

Filip Jurik
Systems administrator/Filemaker developer
Blavatnik School of Government
University of Oxford
T: +44 (0)1865 614501
E: filip.jurik@bsg.ox.ac.uk
W: www.bsg.ox.ac.uk

Office Hours
Monday/Wednesday/Friday: 8:00 – 12:00
Tuesday/Thursday: 13:00 – 17:00

A world better led, better served and better governed.
________________________________

**Comment by danieljtribe** [comment]
Hi Filip,

Yes, that should be fine, I will get those into the next update 👍 

Cheers also for making me aware of Home+, what a great app! 

-Dan

**Comment by bsg-marvin** [comment]
Hi Daniel,
I must thank you because this is what I have been looking for for very long time. I want to be able to switch off my EV charger so when missis get home from work and plugs the car in it won’t simply start until later date alongside with few other automations around the house. Also I looked at your other work and I need to buy inkyphat. :) That way everybody in the house can see current prices. Great work. :)
________________________________
