### ISSUE TITLE
Low Price period switch is always on

### ISSUE THREAD

**Issue by DougMunford** [danieljtribe/homebridge-agile-octopus#2]
Cheers for this plugin, very useful, however the low price period switch appears not to function correctly.
Regardless of what value I set as the threshold it turns on and stays that way.

**Comment by danieljtribe** [comment]
Hi Doug, thank you kindly for your report and please excuse the delay in replying to this issue. I have pushed out an update to the plugin today which re-works the low price and negative price switches and addresses this issue. Please don't hesitate to re-open this or open a new issue if I'm able to help further!
