### ISSUE TITLE
High price threshold in pence

### ISSUE THREAD

**Issue by somekindofrob** [danieljtribe/homebridge-agile-octopus#25]
I would love to have these switches for the other end of the prices as well, for the most expensive time of day. Since we’re heating most of the house with infrared panels it would be nice to be able to switch them automatically off when the price reaches a threshhold.

So that’s basically a switch based on a “High price threshold in pence” additionally to the “Low price threshold in pence”.

Thanks a lot in advance!

**Comment by danieljtribe** [comment]
Hi @somekindofrob ,

Thanks for the suggestion! I've just added this to version 1.2.10 of the plugin, please let me know if I can do anything more to help.

Cheers,
Dan

**Comment by somekindofrob** [comment]
Thank you so much! That was quick!!
There seems to be a bug however. Any high price threshold set above 35p wouldn't work, the switch stays off. I believe this might be connected with the accessory "Current price per unit". This seems to not go over 35 degrees (pence) even when the current rate is higher. Not sure why that is, you might be able to help though :)
All the best!!
