### ISSUE TITLE
BST / Daylight Savings

### ISSUE THREAD

**Issue by samsonrosen** [danieljtribe/homebridge-agile-octopus#7]
This plugin is perfect for me. I’ve just joined agile and I want to start automating. Except I think it’s not recognising BST? See screenshots for 60 minutes. 

It seems to be an hour out? I checked my config for the Pi I’m running it on - and it says GMT+0100 in the system information.

![IMG_8524](https://github.com/danieljtribe/homebridge-agile-octopus/assets/7211878/221aa417-4a9f-4926-90df-df8c57b580aa)
![IMG_8525](https://github.com/danieljtribe/homebridge-agile-octopus/assets/7211878/f0475d19-bde5-4725-af86-ec5d32c46ae1)

**Comment by darrenmcuk** [comment]
Ahh nice spot I was wondering why things were not right.

**Comment by samsonrosen** [comment]
This seems to be working fine now!
